### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZXL-Q** [EB-wilson/TooManyItems#1]
在TMI里面选择按模组排序之后闪退
[benglog.txt](https://github.com/EB-wilson/TooManyItems/files/13326977/benglog.txt)

**Comment by EB-wilson** [comment]
但是，你给我的日志没有任何一处包含崩溃信息

**Comment by ZXL-Q** [comment]
[crash-report-11_12_2023_10_24_15.txt](https://github.com/EB-wilson/TooManyItems/files/13327080/crash-report-11_12_2023_10_24_15.txt)
[Uploading crash-report-11_12_2023_11_31_42.txt…]()
