### ISSUE TITLE
与BetaMindy同时开启游戏必定报错

### ISSUE THREAD

**Issue by hjugjki** [EB-wilson/TooManyItems#6]
[crash-report-02_22_2024_15_35_33.txt](https://github.com/EB-wilson/TooManyItems/files/14370480/crash-report-02_22_2024_15_35_33.txt)

BetaMindy项目地址https://github.com/sk7725/BetaMindy

**Comment by EB-wilson** [comment]
谢谢反馈，来自一个内部未进行的非空检查，现已修复
