### ISSUE TITLE
How to disable the cheat items?

### ISSUE THREAD

**Issue by MuneebM-GAMING** [EB-wilson/TooManyItems#7]
there are those white boxes with red text that are annoying cuz i dont want no cheatz so pls explain how to disable them items pls :)

**Comment by EB-wilson** [comment]
what you mean? um, what is the boxes? can you give me a screenshot?

**Comment by EB-wilson** [comment]
> there are those white boxes with red text that are annoying cuz i dont want no cheatz so pls explain how to disable them items pls :)
what you mean? um, what is the boxes? can you give me a screenshot?

**Comment by EB-wilson** [comment]
> there are those white boxes with red text that are annoying cuz i dont want no cheatz so pls explain how to disable them items pls :)

what you mean? um, what is the boxes? can you give me a screenshot?

**Comment by MuneebM-GAMING** [comment]
oh im so sry i thought that it was part of TMI but it wasnt, because i thought TMI added it... sorry!
