### ISSUE TITLE
Compatibility shenanigans

### ISSUE THREAD

**Issue by BlueTheCube** [EB-wilson/TooManyItems#8]
we need compatibility for MultiCrafterLib. you can see liplum/MultiCrafterLib#42

**Comment by EB-wilson** [comment]
> we need compatibility for MultiCrafterLib. you can see [liplum/MultiCrafterLib#42](https://github.com/liplum/MultiCrafterLib/issues/42)

I think you must to ask Plum, Let him write the TMI adapter, ask he: [LiPlum](https://github.com/liplum)

**Comment by liplum** [comment]
> > we need compatibility for MultiCrafterLib. you can see [liplum/MultiCrafterLib#42](https://github.com/liplum/MultiCrafterLib/issues/42)
> 
> I think you must to ask Plum, Let him write the TMI adapter, ask he: [LiPlum](https://github.com/liplum)

The wiki in English is missing. https://github.com/EB-wilson/TooManyItems/wiki
